/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }



    public static void main(String[] args) {
        Car car = new Car("Car","brandA");
//        car.speedUp(180);
//        System.out.println("\n");
//        car.speedUp(201);
        Vehicle vehicleA = new Vehicle("Vehicle","brandA");
//        Vehicle vehicleB = new Vehicle("B","brandB");
//
//        System.out.println(new App().getGreeting());
//        vehicleA.speedUp(30);
//        System.out.println("\n");
//        vehicleB.speedUp(40);
        Bus bus = new Bus("Bus","brandA");

        Driver vehicleDriver = new Driver (vehicleA,"abc");
        vehicleDriver.speedUp(300);
        System.out.println("\n");
        Driver carDriver = new Driver (car,"abcd");
        carDriver.speedUp(300);
        Driver busDriver = new Driver (bus,"abcde");
        busDriver.speedUp(2);

    }


}

class Driver{
    private Vehicle vehicle;
    private String name;

    public Driver(Vehicle vehicle, String name){
        this.vehicle = vehicle;
        this.name = name;

    }

    public void speedUp(int speed){
        System.out.println("Driver: "+this.name);
        this.vehicle.speedUp(speed);
    }
}


class Car extends Vehicle{

    public Car (String name,String brand){
        super(name, brand);
    }


    @Override
    public void speedUp(int speed){
        if(speed<=200){
            super.speedUp(speed);
        }else{
            System.out.println("Fail to speed up");
        }
    }


}

class Bus extends Vehicle{

    public Bus (String name,String brand){
        super(name, brand);
    }


    @Override
    public void speedUp(int speed){
        if(speed<=2){
            super.speedUp(speed);
        }else{
            System.out.println("Fail to speed up");
        }
    }


}

class Vehicle {

    private String name;
    private String brand;

    public Vehicle (String name,String brand){
        this.name = name;
        this.brand = brand;
    }

    public void speedUp(int speed){
        System.out.println("Car Name: "+this.name+"\n"+"Brand: "+this.brand+"\n"+"Speed: "+speed);
    }
}

