/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }



    public static void main(String[] args) {
        Vehicle vehicleA = new Vehicle("A","Abrand");
        Vehicle vehicleB = new Vehicle("B","Bbrand");

        /*System.out.println(new App().getGreeting());*/
        vehicleA.speedUp(30);
        System.out.println("\n");
        vehicleB.speedUp(40);
    }
}


class Vehicle {

    private String name;
    private String brand;

    public Vehicle (String name,String brand){
        this.name = name;
        this.brand = brand;
    }

    public void speedUp(Integer speed){
        System.out.println("Car Name: "+this.name+"\n"+"Brand: "+this.brand+"\n"+"Speed: "+speed);
    }
}